export const countryCodeMap: Record<string, string> = {
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bahrain: 'bh',
  Belgium: 'be',
  Brazil: 'br',
  Canada: 'ca',
  China: 'cn',
  France: 'fr',
  Germany: 'de',
  'Great Britain': 'gb',
  'United Kingdom': 'gb',
  Hungary: 'hu',
  Italy: 'it',
  Japan: 'jp',
  Mexico: 'mx',
  Monaco: 'mc',
  Netherlands: 'nl',
  Portugal: 'pt',
  Qatar: 'qa',
  Russia: 'ru',
  'Saudi Arabia': 'sa',
  Singapore: 'sg',
  Spain: 'es',
  Turkey: 'tr',
  'United States': 'us',
  'Abu Dhabi': 'ae',
  'United Arab Emirates': 'ae',
};
